### PR TITLE
Added `Bytes` and `get_bytes` method.

### PR DESCRIPTION
**Pull request by Kixunil**
These are useful for faster retrieval of data in some cases, because
they skip conversion to `Vec` (and thus allocation and copying).

I'm not sure if the method should be called `get_bytes`. Maybe `get_native`?

### CODE REVIEW

**Comment by skade** [comment]
This fails on 1.15.0, which I'd still like to support, because of the use of field shorthands.

Other then that, this is _basically_ implementing the leveldb slice type on the Rust side, it could be considered to call it by name.

**Comment by Kixunil** [comment]
Oh, will look at it later.

I disagree that it implements leveldb `Slice`. Leveldb slice is unowned and practically the same thing as Rust slice (one can be easily converted to another). `Bytes` however, is owned. If you dislike `Bytes`, `OwnedSlice` might be another alternative.

**Comment by skade** [comment]
This still fails on another phase now :).

https://travis-ci.org/skade/leveldb/jobs/299840978#L472

I'll see if I fix it myself when I find time.

**Comment by Kixunil** [comment]
Yeah, noticed this before your comment and hopefully fixed.

**Comment by skade** [comment]
Thanks :).

**Pull request merged**
