### PR TITLE
Feature/reverse iter

### PR DESCRIPTION
**Pull request by librelois**
Added the ability to browse an iterator backwards

### CODE REVIEW

**Comment by librelois** [comment]
> Can you remove b782aea from this PR and file the formatting as a separate one?

Done :smile:

**Comment by skade** [comment]
The code in itself looks good. I'm wondering what the use-case is to reverse in the middle of an operation?

The reason I'm asking is that this blows up the iterator struct by a field, while another solution would be to have an `Iterator` and a `ReverseIterator`, that encode this information on the type level?

**Comment by librelois** [comment]
> I'm wondering what the use-case is to reverse in the middle of an operation?

I have this use case.I migrate to Rust a libre crypto-currency engine ([Duniter](https://github.com/duniter/duniter/)) that performs complex treatments on large collections that it reverses in the middle for performance reasons.

> while another solution would be to have an Iterator and a ReverseIterator, that encode this information on the type level?

It's a good idea, and we can do this while keeping the possibility of reversing in the middle.  I've just coded an attempt on the branch [feature/reverse-iter-2](https://github.com/librelois/leveldb/commit/9e4f2983e9c1588ba80704c9a931f7a67426e342), but it requires to duplicate a lot of code so I made some macros :)

**Comment by skade** [comment]
> I have this use case.I migrate to Rust a libre crypto-currency engine (Duniter) that performs complex treatments on large collections that it reverses in the middle for performance reasons.

Interesting, thanks for showing me!

> It's a good idea, and we can do this while keeping the possibility of reversing in the middle. I've just coded an attempt on the branch feature/reverse-iter-2, but it requires to duplicate a lot of code so I made some macros :)

That looks good, can you PR this as a followup?

**Comment by skade** [comment]
I merged this branch by hand and released in the last release.

**Pull request closed without merging**
